### ISSUE TITLE
Carrier profile not working

### ISSUE THREAD

**Issue by ghoraba-55** [Wishmasterflo/Firmware_flasher#2]
First I want to thank you for your effort 
I have this problem that my 8 pro In2020 won't activate my carrier profile on custom roms despite the profile is supported and working on oos and you can find the mbn file in the modem firmware but not on  QPST PDC software 
I have solved this manually by using efs tools and the mbn file i pulled from the modem firmware
I hope you can help cause now every time i update rom or firmware or just randomly it will recert back to using default peofile 
Hope you have a great day 👍👍

**Comment by Wishmasterflo** [comment]
That is nothing I can help with. 
Also I just take the original OOS Stock files to use for the Firmware flasher I dont change anything inside the Firmware files itself. 

That need to be fixed on the custom ROM you use. So check with the dev of the ROM.
