### ISSUE TITLE
No 581 firmware for NA OP8T

### ISSUE THREAD

**Issue by Gtoonm** [Wishmasterflo/Firmware_flasher#3]
The mega list doesn't have the latest F68 581 firmware for the OnePlus 8T. Can you please update it?

**Comment by Wishmasterflo** [comment]
The Firmware for NA/Global is not updated as frequently as the IN and EU ones on the OOS repo where I fetch the full OOS files to build the Firmware from as for NA/Global they use another Server for the update files so those are not updated as frequent as the EU and IN ones.
Afaik many NA/Global users just use the EU Firmware instead.

**Comment by OneHoopyFrood** [comment]
Hey bud! This is awesome! I don't see the NA for 8T devices still. I know it's gotten to be an old device now, but it's still doing everything I need! Is it safe to use the EU firmware for my KB2005?

**Comment by Wishmasterflo** [comment]
Yes, should work fine to use the EU Firmware.
I lnow a lot others use it.

Skickat från Proton Mail Android

-------- Ursprungligt meddelande --------
Den 2024-09-10 05:42, Cole Panike  skrev:
