### ISSUE TITLE
How to go from EvoX ROM to stock? 

### ISSUE THREAD

**Issue by Hot12345** [Wishmasterflo/Firmware_flasher#6]
Hi,
How to go to stock? While running a Oneplus 8 Pro with Evo x ROM (Android 13) on it?
PS: Can I make a donation to your work to support your work?

**Comment by Hot12345** [comment]
PS: My Oneplus 8 Pro Recovery is this, Is this recovery obsolete?: 
![image](https://github.com/Wishmasterflo/Firmware_flasher/assets/29144713/9d39447a-b390-412d-adac-6cb7f3af9b00)

**Comment by Wishmasterflo** [comment]
Hi!
You have my Paypal link here for Donations.  [](https://www.paypal.com/paypalme/Wishmasterflo )
To go back to Stock you should use MSMtool.  
In some cases it also works to flash the full OOS zip file (which you can find for your device on XDA repo of OxygenOS)  via Orangefox recovery. 
For Oneplus 8Pro you would need [this](https://drive.google.com/drive/folders/1eSe_XNSYJkgQzYdLyRXLqwsd52VJwzBT) Orangefox recovery.

**Comment by Wishmasterflo** [comment]
.
