### ISSUE TITLE
Orange state with fw_Oneplus8T_EU_OOS13.1_F69_582.zip

### ISSUE THREAD

**Issue by KrazyLurt** [Wishmasterflo/Firmware_flasher#7]
went from 581 to fw_Oneplus8T_EU_OOS13.1_F69_582.zip , and it gave me the orange state abl.img

double checked and adb sideloaded the zip again.

Went into fastbootd and flashed the 581 abl.img on both slots, and no more orange state.

**Comment by Wishmasterflo** [comment]
Ahh yes, seems that the one who packed that Firmware did forget to replace the correct abl.img file.  I will fix that when I have time.

**Comment by Wishmasterflo** [comment]
This is fixed and the files are reuploaded now!
