### ISSUE TITLE
OnePlus 9/9 pro Android 14.

### ISSUE THREAD

**Issue by Vishalcj17** [Wishmasterflo/Firmware_flasher#9]
Can you please add the android 14 firmware (stable) to your mega link please? Would be really helpful. Thanks0

**Comment by Wishmasterflo** [comment]
Yes I will do that in the next days, but anyway should not really be needed now for anything as I dont think there are any custom ROMs based on OOS14 yet.

**Comment by Vishalcj17** [comment]
> Yes I will do that in the next days, but anyway should not really be needed now for anything as I dont think there are any custom ROMs based on OOS14 yet.

AOSPA is based off OOS14 now.

**Comment by Wishmasterflo** [comment]
Have uploaded OOS14 IN Firmware for OP8T and OP9 series now.

**Comment by CodexHere** [comment]
Any chance for NA firmware update for OOS14?

**Comment by Wishmasterflo** [comment]
> Any chance for NA firmware update for OOS14?

Hi!
On the OOS repo page on XDA there is no download for the OOS14 NA Version. 
The NA Versions are not getting updated there as frequently as the IN and EU Versions, but if someone can provide me witrh a download link for the full OOS14 NA zip then I can create a flashable Firmware file out of it.

**Comment by OneHoopyFrood** [comment]
> if someone can provide me witrh a download link for the full OOS14 NA zip then I can create a flashable Firmware file out of it.

Interesting development the last couple weeks where they've disabled normal access to the firmwares. 

See: https://oxygenupdater.com/article/474/

But the workaround does present a possible opportunity? It's possible to download the incremental update for 14 NA using this method. The full one still seems to be 13.1, but could the OTA incremental offer something useable?

I'm not quite familiar enough with how all these images work to know if it's possible to create a flashable image (or zip?) from an established system. Is it?

**Comment by Wishmasterflo** [comment]
Yes I know but no problem.
There is a workaround when removing component from the download link it works again.

Skickat från Proton Mail Android

-------- Ursprungligt meddelande --------
Den 2024-09-10 06:20, Cole Panike  skrev:

**Comment by OneHoopyFrood** [comment]
I think maybe you misunderstood my comment?

I know that the workaround works fine. I'm asking if the workaround reveals an opportunity to put together the OTA update for OOS-14 with the base image to produce what is needed to extract firmware for upgrading NA devices.

I'm on Nameless AOSP legacy right now. It's android 13 based. The latest is 14 based and I wanted to upgrade, but that requires the firmware update. To get that update through official channels I would need to flash OOS, the upgrade using the incremental strategy, then re-flash Nameless 14 based.

I was hoping to skip that business with OOS without having to use the EU firmware. But if you say the EU firmware should be ok, I can try that.
